### ISSUE TITLE
文档命令多个空格

### ISSUE THREAD

**Issue by leslieeilsel** [sunshinev/laravel-gii#8]
README中，这行命令，`publish`前面多了一个空格
```shell
php artisan vendor: publish --tag laravel-gii
```

**Comment by sunshinev** [comment]
> README中，这行命令，`publish`前面多了一个空格
> 
> ```shell
> php artisan vendor: publish --tag laravel-gii
> ```

感谢~已经修改文档 去掉了空格~
如果使用中有其他问题，欢迎指正~~
